services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565/tcp" # game port
      - "24454:24454/udp" # simple-voice-chat port
    environment:
      EULA: true

      VERSION: "1.21.1"
      TYPE: "FABRIC"
      INIT_MEMORY: "4G"
      MAX_MEMORY: "8G"

      ENABLE_AUTOPAUSE: true
      AUTOPAUSE_TIMEOUT_EST: 300
      AUTOPAUSE_TIMEOUT_INIT: 90
      AUTOPAUSE_TIMEOUT_KN: 90
      MAX_TICK_TIME: -1 # disable tick time to avoid crashing

      DIFFICULTY: "hard"
      ONLINE_MODE: false # allow cracked clients

      RCON_PASSWORD: "huckmeplease"

      MODRINTH_ALLOWED_VERSION_TYPE: alpha
      MODRINTH_PROJECTS: |
        fabric-api
        surveyor
        cloth-config
        cardinal-components-api
        moonlight
        jamlib
        architectury-api
        puzzles-lib
        cristel-lib
        collective
        forge-config-api-port
        bclib
        wunderlib
        worldweaver
        balm

        noisium
        ferrite-core

        terralith
        fallingtree
        rightclickharvest
        towns-and-towers
        villager-names-serilum
        spawn-animations
        netherportalfix

        simple-voice-chat
        voice-chat-interaction
        antique-atlas-4
        travelersbackpack
        supplementaries
        amendments
        fabric-seasons
        fabric-seasons-extras
        toms-storage
        easy-magic
        easy-anvils
        another-furniture
        yigd
        betternether
        betterend
        farmers-delight-refabricated
        fabric-seasons-delight-compat
        waystones
        jei

    volumes:
      - ./data:/data # server data
