services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: true
      ONLINE_MODE: false
      INIT_MEMORY: 2G
      MAX_MEMORY: 4G

      DIFFICULTY: hard

      RCON_PASSWORD: "huckmeplease"
    volumes:
      - ./data:/data
